INSERT INTO ORDERITEM (ORDERID, MEALID, PRICE, QUANTITY) 
SELECT ?, cm.MEALID, m.PRICE, cm.QUANTITY 
FROM CARTMEAL cm
JOIN MEAL m ON cm.MEALID = m.MEALID
WHERE CARTID = (SELECT CARTID FROM CART WHERE CUSTOMERID = ?);