UPDATE CART
SET TOTALPRICE = (
    SELECT COALESCE(SUM(m.PRICE * cm.QUANTITY), 0)
    FROM CARTMEAL cm
    JOIN MEAL m ON cm.MEALID = m.MEALID
    WHERE cm.CARTID = CART.CARTID
)
WHERE CUSTOMERID = ?;